- files/board/arc/overlayfs/opt/arc/arc.sh
> arc: little fix

- files/board/arc/make-img.sh
- files/board/arc/overlayfs/opt/arc/arc.sh
> arc: try to fix the gpio error while build

- files/board/arc/overlayfs/opt/arc/arc.sh
> arc: fix script

- img-gen.sh
> img-gen: fix typo

- files/board/arc/overlayfs/opt/arc/model-configs/RS4021xs+.yml
> arc: fix 4021

- img-gen.sh
> img-gen: fix

- img-gen.sh
> img-gen: more fixes

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS918+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS920+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS923+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
> models: change dom back to 2

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
> models: broadwellnk: dom to 1

- files/board/arpl/overlayfs/opt/arpl/init.sh
> init: change to lkm prod

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS923+.yml
> models: DS923+: add missing -fma flag

- files/board/arpl/overlayfs/opt/arpl/arc.sh
> arc: systeminformation: remove additional space

- README.md
> readme: update latest changes

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1520+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS2422+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS918+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS920+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
> arc: models: remove old builds

- files/board/arpl/overlayfs/root/.bashrc
> arc: fix webinterface

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1520+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS2422+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS918+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS920+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS923+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
> models: update configs again

- files/board/arpl/overlayfs/opt/arpl/arc.sh
> arc: update diskconfig

- docker/syno-compiler/build.sh
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1520+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS2422+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS918+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS920+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
- make_rsss.sh
- rss.json
- rss.xml
> arc: model-config: update and add back old dsm versions

- files/board/arpl/overlayfs/opt/arpl/arc.sh
for user who have old addon files in system
> arc: readd function to map usb drives as internal

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3617xs.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
This reverts commit e8693ee1fc1e0fc9b865e0076cfaea715886db3e.
> Revert "arc: model-configs: resync with community"

- files/board/arpl/overlayfs/opt/arpl/arc.sh
(makes more problems than is helping us)
> arc: remove SasIdxMap

- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1019+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1520+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS1621xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS2422+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS3622xs+.yml.disabled
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS723+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS918+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS920+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DS923+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3219.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS1221+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS1619xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS3621xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/RS4021xs+.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/SA3400.yml
- files/board/arpl/overlayfs/opt/arpl/model-configs/SA6400.yml
This reverts commit bbcad8c94bb84d3801800b3ac9748d4ddd9b521f.
> Revert "arc: model-configs: remove bde_internal_10g"

- files/board/arpl/overlayfs/opt/arpl/init.sh
if we use dev - powerbutton will not work
> arc: set lkm back to prod

- files/board/arpl/overlayfs/opt/arpl/ramdisk-patch.sh
This reverts commit 937b031f605edf16ba9bdd4ae648e9965defb422.
> Revert "ramdisk-patch: go back to old ordering"

- files/initrd/opt/arc/include/functions.sh
(spainish user can say thanks to apriliars3 / Miguel Angel)
> block: spain also from usage
